-- ==========================================
-- 1. EXTENSIONS
-- ==========================================
create extension if not exists "vector" with schema extensions;
create extension if not exists "uuid-ossp" with schema extensions;

-- ==========================================
-- 2. TABLES CREATION
-- ==========================================

-- TENANTS: The main organization/client
create table public.tenants (
    id uuid not null default extensions.uuid_generate_v4() primary key,
    name text not null,
    slug text not null unique,
    logo_url text,
    created_at timestamp with time zone default now()
);

-- PROFILES: Users of the dashboard (admins of the tenants)
create table public.profiles (
    id uuid not null references auth.users(id) on delete cascade primary key,
    tenant_id uuid references public.tenants(id) on delete cascade,
    full_name text,
    avatar_url text,
    role text default 'admin'::text,
    updated_at timestamp with time zone default now()
);

-- CUSTOMERS: End-users who chat with the AI
create table public.customers (
    id uuid not null default extensions.uuid_generate_v4() primary key,
    tenant_id uuid references public.tenants(id) on delete cascade,
    external_id text not null,
    name text,
    email text,
    metadata jsonb default '{}'::jsonb,
    created_at timestamp with time zone default now(),
    unique (tenant_id, external_id)
);

-- KNOWLEDGE ITEMS: High-level representation of uploaded files (PDFs, docs)
create table public.knowledge_items (
    id uuid not null default extensions.uuid_generate_v4() primary key,
    tenant_id uuid references public.tenants(id) on delete cascade,
    filename text not null,
    file_url text,
    status text default 'processing'::text,
    metadata jsonb default '{}'::jsonb,
    created_at timestamp with time zone default now()
);

-- DOCUMENTS: Chunks of text from knowledge items + vector embeddings
create table public.documents (
    id bigint generated by default as identity primary key,
    tenant_id uuid references public.tenants(id) on delete cascade,
    knowledge_item_id uuid references public.knowledge_items(id) on delete cascade,
    content text not null,
    metadata jsonb default '{}'::jsonb,
    embedding extensions.vector(1536), -- Assuming OpenAI text-embedding-3-small
    created_at timestamp with time zone default now()
);

-- CONVERSATIONS: Container for a chat session
create table public.conversations (
    id uuid not null default extensions.uuid_generate_v4() primary key,
    tenant_id uuid references public.tenants(id) on delete cascade,
    customer_id uuid references public.customers(id) on delete cascade,
    session_id text not null unique,
    created_at timestamp with time zone default now()
);

-- MESSAGES: Individual messages within a conversation (Bot / User)
create table public.messages (
    id uuid not null default extensions.uuid_generate_v4() primary key,
    conversation_id uuid references public.conversations(id) on delete cascade,
    role text not null, -- 'user', 'assistant', 'system'
    content text not null,
    citations jsonb default '[]'::jsonb,
    created_at timestamp with time zone default now()
);

-- ==========================================
-- 3. ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

alter table public.tenants enable row level security;
alter table public.profiles enable row level security;
alter table public.customers enable row level security;
alter table public.knowledge_items enable row level security;
alter table public.documents enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

-- Policies for Tenants
create policy "Users can view their own tenant" on public.tenants for select using (
    id in (select tenant_id from public.profiles where id = auth.uid())
);

-- Policies for Profiles
create policy "Users can view their own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id);

-- Policies for Customers
create policy "Users can view their tenant's customers" on public.customers for select using (
    tenant_id in (select tenant_id from public.profiles where id = auth.uid())
);

-- Policies for Knowledge Items
create policy "Users can view their tenant's knowledge items" on public.knowledge_items for select using (
    tenant_id in (select tenant_id from public.profiles where id = auth.uid())
);
create policy "Users can manage their tenant's knowledge items" on public.knowledge_items for all using (
    tenant_id in (select tenant_id from public.profiles where id = auth.uid())
);

-- Policies for Documents
create policy "Users can manage their tenant's documents" on public.documents for all using (
    tenant_id in (select tenant_id from public.profiles where id = auth.uid())
);

-- Policies for Conversations
create policy "Users can view their tenant's conversations" on public.conversations for select using (
    tenant_id in (select tenant_id from public.profiles where id = auth.uid())
);

-- Policies for Messages (Check via conversations -> tenant_id)
create policy "Users can view their tenant's messages" on public.messages for select using (
    conversation_id in (
        select id from public.conversations where tenant_id in (
            select tenant_id from public.profiles where id = auth.uid()
        )
    )
);

-- ==========================================
-- 4. DATABASE FUNCTIONS & TRIGGERS
-- ==========================================

-- Auto-create profile on user signup
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- Vector Search Function (Multi-tenant aware!)
create or replace function public.match_documents(
  query_embedding extensions.vector,
  match_count integer default 5,
  filter_tenant_id uuid default null
)
returns table(id bigint, content text, metadata jsonb, similarity double precision)
language plpgsql as $$
begin
  return query
  select
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) as similarity
  from public.documents d
  where (filter_tenant_id is null or d.tenant_id = filter_tenant_id)
  order by d.embedding <=> query_embedding
  limit match_count;
end;
$$;
